{% set name = "ExifRead" %}
{% set version = "3.1.0" %}
{% set hash = "64d886c2bf2cc07655bd7d0859f6ba6db3b31ed64b58007868534a0ed0dc0eba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | lower }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - exifread
  commands:
    - EXIF.py --help

about:
  home: https://github.com/ianare/exif-py
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Read Exif metadata from tiff and jpeg files.
  description: |
    Easy to use Python module to extract Exif metadata from tiff and jpeg files.

extra:
  recipe-maintainers:
    - anjos
    - goanpeca
    - rlaverde
