{% set name = "ExifRead" %}
{% set version = "2.3.2" %}
{% set hash = "a0f74af5040168d3883bbc980efe26d06c89f026dc86ba28eb34107662d51766" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - exifread
  commands:
    - EXIF.py --help

about:
  home: https://github.com/ianare/exif-py
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Read Exif metadata from tiff and jpeg files.
  description: |
    Easy to use Python module to extract Exif metadata from tiff and jpeg files.

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
