{% set name = "ExifRead" %}
{% set version = "2.3.0" %}
{% set hash = "ed2806f5683af265498d5198538a20d5bcc87e0f767384f2f94641acd4937113" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - exifread
  commands:
    - EXIF.py --help

about:
  home: https://github.com/ianare/exif-py
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Read Exif metadata from tiff and jpeg files.
  description: |
    Easy to use Python module to extract Exif metadata from tiff and jpeg files.

extra:
  recipe-maintainers:
    - goanpeca
    - rlaverde
